---
driver_plugin: docker
provisioner: chef_zero
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.10
  driver_config:
    image: ubuntu:12.10
    platform: ubuntu
    provision_command:
      - "apt-get install -y cron build-essential"
  run_list:
  - recipe[apt]

- name: debian-6.0.7
  driver_config:
    image: tianon/debian:6.0.7
    platform: debian
    provision_command:
      - "apt-get install -y cron build-essential"
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[tarsnap]
  - recipe[minitest-handler]
  attributes:
    tarsnap_keys:

